# Generated by Django 6.0.3 on 2026-03-03 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('gps_coordinates', models.CharField(blank=True, help_text='e.g. 35.6762,139.6503', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('certification_number', models.CharField(help_text='EU Organic / USDA / JAS etc.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='e.g. Heirloom Cherry Tomatoes', max_length=150)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('planted_date', models.DateField()),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination', models.CharField(blank=True, help_text='Restaurant name or Export buyer', max_length=200)),
                ('qr_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='my_farm.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='farmhand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='my_farm.farmhand'),
        ),
        migrations.CreateModel(
            name='TreatmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('planting', 'Planting'), ('fertilizer', 'Organic Fertilizer'), ('pest_control', 'Organic Pest Control'), ('irrigation', 'Irrigation'), ('weeding', 'Manual Weeding'), ('harvest', 'Harvest'), ('packing', 'Packing'), ('transport', 'Transport')], max_length=50)),
                ('product_used', models.CharField(blank=True, help_text='e.g. Compost Tea – 10L', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_logs', to='my_farm.batch')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
