# Generated by Django 6.0.3 on 2026-03-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_farmhand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('username', models.CharField()),
                ('certification', models.CharField(help_text='EU Organic / USDA / JAS etc.', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
