# Generated by Django 6.0.3 on 2026-03-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0003_alter_new_farmhand_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_farmhand',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
